### ISSUE TITLE
Could you make your microchip patch going mainline?

### ISSUE THREAD

**Issue by liubenyuan** [fpgadeveloper/myd-y7z010-projects#1]
Thanks for your modification to KSZ9031! I am using myir zturn lite board, it is also using microchip KSZ9031.

Without proper configuration of ksz9031, it may encounter a `ethernet link up` and `ethernet link down` messages. I am going to test your patch on official Xilinx embeddedsw.

Have you got any plan of making this patch mainline?

**Comment by liubenyuan** [comment]
I test your code and it solved my problem of using lwip202 on Zturn Lite 7z007S!

https://github.com/Xilinx/embeddedsw/issues/70#issuecomment-440555103

Thank you.

**Comment by fpgadeveloper** [comment]
Thanks for letting me know. I'm glad that you found it useful.

No, I'm not going to make a pull request to the mainline but you can do it if you like!

**Comment by liubenyuan** [comment]
They do not accept the third party eth drivers other than TI, Marvel.

Anyway, thanks for your code and they indeed solve my problems of using zturn product and Vivado 2018.02
